<script setup lang="ts">
import { ActivationMethod, type License, useInventory } from '@moonbase.sh/vue'

const { activateProduct } = useInventory()

const step = ref<'input' | 'uploading' | 'done'>('input')
const error = ref<Error | null>(null)
const result = ref<{ license: License, url: string } | null>(null)

async function handleToken(token: string) {
  error.value = null
  step.value = 'uploading'
  try {
    result.value = await activateProduct(token, ActivationMethod.Offline)
    step.value = 'done'
  }
  catch (err) {
    error.value = err as Error
    step.value = 'input'
  }
}

function reset() {
  error.value = null
  result.value = null
  step.value = 'input'
}
</script>

<template>
  <div class="manual-activation">
    <p class="hint">
      Upload your machine file here to get a license file for activating offline devices.
      The machine file is generated by the plugin running on the device.
    </p>

    <ActivationDeviceTokenInput
      v-if="step === 'input'"
      :error="error"
      @input="handleToken"
      @error="error = $event"
    />

    <div v-else-if="step === 'uploading'" class="activation-loader">
      <p>Generating license…</p>
    </div>

    <div v-else-if="step === 'done' && result" class="manual-activation-result">
      <h3>Success</h3>
      <p>Your license is ready to download.</p>
      <ActivationProductCard v-if="result.license.product" :product="result.license.product">
        <template #description>
          <p class="hint">
            {{ result.license.activeNumberOfActivations }} of
            {{ result.license.maxNumberOfActivations }} devices activated
          </p>
        </template>
        <a
          class="submit"
          :href="result.url"
          target="_blank"
          rel="noopener"
          download="license-file.mb"
        >
          Download license file
        </a>
      </ActivationProductCard>
      <button type="button" class="logout" @click="reset">
        Activate another device
      </button>
    </div>
  </div>
</template>
